### ISSUE TITLE
rails 4

### ISSUE THREAD

**Issue by azinazadi** [craigchristenson/Spree-2Checkout#1]
Hello , 

thanks for the gateway, is there any plans to support rails4 and ruby2?

thank you.

**Comment by craigchristenson** [comment]
Yea I just tested master against a fresh install of spree running on ruby 2.1.0 and rails 4.0.4 per their tutorial and everything works great for me.
http://guides.spreecommerce.com/developer/getting_started_tutorial.html

Please let me know if you are experiencing issues so I can take care of them for you.
